test: lets test the executing bun add

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,17 @@ jobs:
       - name: Install dependencies
         run: bun install
 
-      - name: Run check
+      - name: Run tests
         run: bun test
         env:
           SOCKET_CLI_API_TOKEN: ${{ secrets.SOCKET_CLI_API_TOKEN }}
+
+      - name: Test blocking on install
+        run: |
+          if bun add lodahs; then
+            echo "ERROR: Scanner failed to block malicious package"
+            exit 1
+          else
+            echo "SUCCESS: Scanner blocked malicious package as expected"
+            exit 0
+          fi
